bagficks4
Khavkin/team-9-project pull request #33
Opened 2023-02-22 14:24 UTC by FurmanAndrew

bagficks #4 for weather

2023-02-22 19:05 UTC, Khavkin requested changes

2023-02-22 19:05 UTC, Khavkin commented on src/js/components/weather.js
> +            <a class="weather__link-but" href="https://ua.sinoptik.ua/%D0%BF%D0%BE%D0%B3%D0%BE%D0%B4%D0%B0-%D0%BA%D0%B8%D1%97%D0%B2"
Назви вже weather__link-button

2023-02-22 19:05 UTC, Khavkin commented on src/js/components/weather.js
>      buttonForWeatherSevenDay: document.querySelector('.weather__button'),
якщо такого класса  .weather__button вже немає, то не треба його шукати

2023-02-23 19:54 UTC, AndriiKachan1996 approved these changes

2023-02-24 01:17 UTC, AnastasiaMosevych commented on src/index.js
> +import debounce from 'lodash.debounce';
в мейні вже нема lodash.debounce. треба звичайний використати дібаунс.

2023-02-24 01:26 UTC, Khavkin commented
не актуально

2023-02-24 01:26 UTC, closed without merging